project:
  type: book

book:
  title: "Generative structured data extraction using LLMs"
  author: "Mara Wilhelmi, Sherjeel Shabih, Martino Rıos Garcıa, Santiago Miret,Christoph Koch, Pepe Marquez, and Kevin Maik Jablonka"
  date: "4/11/2024"
  chapters:
    - index.qmd
    - part: Data extraction workflow
      chapters:
        - obtaining_data/obtaining_data.qmd          
        - obtaining_data/crossref_search.ipynb
        - obtaining_data/data_mining.ipynb
        - obtaining_data/annotation.ipynb
        - constrained_decoding/index.ipynb
        - document_parsing_and_cleaning.qmd
        - beyond_text/beyond_images.ipynb
    - part: Case Studies  
      chapters:
        - ocr/nougat/nougat.ipynb

# bibliography: references.bib
# csl: nature.csl

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt


